### PR TITLE
Adds ignore_primary_key in create mutation

### PR DESCRIPTION
**Pull request by e3oroush**
I needed to be able to customize primary key adding in create mutation.  
I just added it as an optional argument.  
Please accept the PR.

### CODE REVIEW

**Comment by tOgg1** [comment]
Hi,

You are of course right in that the `primary_key` handling of the create mutation is a bit too naive, in that it doesn't allow for any explicit setting, regardless of whether or not one uses an auto field or not. So I am inclined to merge this. However, I need the following from you:

* The `ignore_primary_key` attribute needs to be added to `DjangoCreateMutationOptions`.
* A unit test testing this functionality.

**Comment by e3oroush** [comment]
Thanks for answering.  
I'm not sure where and how I'm supposed to put the unit test of adding this attribute.  
Can you tell me what functionality of this feature do you have in your mind for testing?  
Should I just add it to `TestCreateMutationManyToOneExtras` and `TestCreateWithOneToOneField` test cases or add another test case?

**Comment by tOgg1** [comment]
Hi, pardon the delayed response.

There is some missing infrastructure here, in particular some general test classes for the create mutation. So instead of you implementing the tests here, I'll create a new PR with some tests.

So as long as you add the attribute to `DjangoCreateMutationOptions` we are ready to merge.

**Comment by e3oroush** [comment]
Sorry it took me so long to respond, I haven't noticed it.   
Hope it's what you want.  
And thanks for your great package,.

**Pull request merged**
